# Generated by Django 6.0 on 2026-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_customuser_date_of_birth_customuser_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
