# Generated by Django 6.0 on 2026-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_emergencycontact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone",
            field=models.CharField(max_length=13),
        ),
    ]
