# Generated by Django 6.0 on 2026-04-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_emergencycontact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="ride_preference",
        ),
    ]
