# Generated by Django 6.0 on 2026-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(blank=True, max_length=10)),
                ("data", models.TextField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Archived User",
                "verbose_name_plural": "Archived Users",
                "db_table": "past_table",
            },
        ),
    ]
