# Generated by Django 6.0 on 2026-04-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_pasttable"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PastTable",
            new_name="PastUser",
        ),
        migrations.AlterModelTable(
            name="pastuser",
            table="past_user",
        ),
    ]
