# Generated by Django 6.0 on 2026-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_pastuser_address_pastuser_avatar_pastuser_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_address",
            field=models.TextField(blank=True),
        ),
    ]
