# Generated by Django 6.0 on 2026-04-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_customuser_is_superuser"),
    ]

    operations = [
        # Essential tables for Django migrations and authentication to function correctly
        # migrations.RunSQL(
        #     sql="DROP TABLE IF EXISTS auth_group;",
        #     reverse_sql="",
        # ),
        # migrations.RunSQL(
        #     sql="DROP TABLE IF EXISTS auth_group_permissions;",
        #     reverse_sql="",
        # ),
        # migrations.RunSQL(
        #     sql="DROP TABLE IF EXISTS auth_permission;",
        #     reverse_sql="",
        # ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS django_admin_log;",
            reverse_sql="",
        ),
        # migrations.RunSQL(
        #     sql="DROP TABLE IF EXISTS django_content_type;",
        #     reverse_sql="",
        # ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS django_session;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS users_groups;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS users_user_permissions;",
            reverse_sql="",
        ),
    ]
