# Generated by Django 6.0 on 2026-04-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_unused_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=255)),
                ("loginid", models.EmailField(max_length=254, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("role", models.CharField(default="admin", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
                "db_table": "admin",
            },
        ),
    ]
