# Generated by Django 6.0 on 2026-04-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_seed_admin_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastuser",
            old_name="address",
            new_name="home_address",
        ),
        # Safety: Create dummy tables if they are missing so the RemoveField below doesn't crash
        migrations.RunSQL("CREATE TABLE IF NOT EXISTS users_groups (id integer);"),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS users_user_permissions (id integer);"
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
    ]
