# Generated by Django 6.0 on 2026-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_rename_address_pastuser_home_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="pastuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="pastuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="pastuser",
            name="password",
        ),
        migrations.RemoveField(
            model_name="pastuser",
            name="status",
        ),
    ]
