# Generated by Django 6.0 on 2026-04-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_driverwallet_drivertransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="failed_pin_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drivertransaction",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(),
        ),
    ]
