# Generated by Django 6.0 on 2026-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallet_failed_pin_attempts_wallet_pin_locked_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_method",
            field=models.CharField(default="wallet", max_length=20),
        ),
    ]
