# Generated by Django 6.0 on 2026-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverwallet',
            name='failed_pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverwallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverwallet',
            name='pin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverwallet',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
