# Generated by Django 6.0 on 2026-04-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="address",
        ),
        migrations.AlterModelTable(
            name="driverprofile",
            table="driver",
        ),
    ]
