# Generated by Django 6.0 on 2026-04-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driverprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="user",
        ),
    ]
