# Generated by Django 6.0 on 2026-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_remove_driverprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=10)),
                ("last_name", models.CharField(blank=True, max_length=10)),
                ("password", models.CharField(blank=True, max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                ("vehicle_plate", models.CharField(blank=True, max_length=10)),
                ("license_no", models.CharField(blank=True, max_length=15)),
                ("total_rides", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Archived Driver",
                "verbose_name_plural": "Archived Drivers",
                "db_table": "past_driver",
            },
        ),
    ]
