# Generated by Django 6.0 on 2026-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_pastdriver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastdriver",
            name="password",
        ),
        migrations.AddField(
            model_name="pastdriver",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pastdriver",
            name="role",
            field=models.CharField(default="driver", max_length=10),
        ),
        migrations.AddField(
            model_name="pastdriver",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
