# Generated by Django 6.0 on 2026-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0006_remove_pastdriver_password_pastdriver_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hatchback", "Hatchback"),
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("suv-muv", "SUV/MUV"),
                    ("muv", "MUV"),
                ],
                default="sedan",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pastdriver",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
