# Generated by Django 6.0.3 on 2026-03-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup", models.CharField(max_length=255)),
                ("dropoff", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField(blank=True, null=True)),
                ("pickup_lng", models.FloatField(blank=True, null=True)),
                ("dropoff_lat", models.FloatField(blank=True, null=True)),
                ("dropoff_lng", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("distance", models.FloatField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("ride_type", models.CharField(default="standard", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rides",
                "ordering": ["-created_at"],
            },
        ),
    ]
