# Generated by Django 6.0 on 2026-04-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_remove_driverprofile_user"),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides_as_driver",
                to="drivers.driverprofile",
            ),
        ),
    ]
