# Generated by Django 6.0 on 2026-04-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_ride_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="cancellation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ride",
            name="cancelled_by",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="ride",
            name="is_return_ride",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ride",
            name="linked_ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_return",
                to="rides.ride",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="passengers",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ride",
            name="payment_method",
            field=models.CharField(
                choices=[("wallet", "Wallet"), ("upi", "UPI"), ("cash", "Cash")],
                default="wallet",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(default="sedan", max_length=20),
        ),
    ]
